import { Component, ChangeDetectionStrategy, computed, inject } from '@angular/core';
import { NavigationEnd, Router, RouterOutlet, type ActivatedRouteSnapshot } from '@angular/router';
import { filter, map } from 'rxjs';
import { toSignal } from '@angular/core/rxjs-interop';
import { SidenavComponent } from '@core/layout/sidenav.component';
import { MobileNavComponent } from '@core/layout/mobile-nav.component';
import { HeaderComponent } from '@core/layout/header.component';
import { MinimizedRoomBarComponent } from '@core/layout/minimized-room-bar.component';
import { ImBootstrapService } from '@core/realtime/im-bootstrap.service';
import { ToastContainerComponent } from '@shared/ui/toast/toast-container.component';
import { PwaUpdateBannerComponent } from '@shared/ui';
import { NotificationToastComponent } from '@shared/ui/notification-panel';
import { PwaUpdateService } from '@core/services/pwa-update.service';
import { ActiveCallStore } from '@store/active-call.store';
import { injectIsMobileViewport } from '@shared/utils';

function isRouteFlagSet(root: ActivatedRouteSnapshot, key: 'immersive' | 'fullscreen'): boolean {
  let node = root;
  while (node.firstChild) node = node.firstChild;
  return node.data[key] === true;
}

@Component({
  selector: 'app-root',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterOutlet, SidenavComponent, MobileNavComponent, HeaderComponent, ToastContainerComponent, PwaUpdateBannerComponent, MinimizedRoomBarComponent, NotificationToastComponent],
  template: `
    <div
      class="grid h-svh grid-cols-1 overflow-hidden"
      [class.immersive]="immersive()"
      [class.fullscreen]="fullscreen()"
    >
      <!-- Sidenav's own mobile-folding logic lives inside app-sidenav.component.*;
           the shell only suppresses it on fullscreen routes (login/signup are
           chromeless) and immersive routes on mobile. -->
      <app-sidenav [hidden]="hideSidenav() || fullscreen()" />
      <div class="main-wrapper relative block min-h-0 overflow-hidden">
        <app-header [hidden]="fullscreen()" />
        <main
          id="main-content"
          class="app-main-shell h-full min-h-0 overflow-y-auto overflow-x-hidden overscroll-y-contain"
          tabindex="-1"
        >
          <router-outlet />
        </main>
        <!-- Mobile-nav: hidden on lg+ (sidenav takes over), on fullscreen routes, and on
             immersive routes when the viewport is mobile (so rooms get the full viewport height).
             The third case used to be expressed as @media (max-width: 1023.98px) inside
             mobile-nav.component.ts — replaced by the [immersive] input below so the rule
             follows viewport state directly instead of a media-query dance. -->
        <app-mobile-nav
          class="block lg:hidden"
          [hidden]="fullscreen()"
          [immersive]="hideSidenav()" />
      </div>
    </div>
    <app-toast-container />
    <app-notification-toast />
    @if (activeCallStore.minimized()) {
      <app-minimized-room-bar />
    }
    @if (pwaUpdate.shouldShowBanner()) {
      <app-pwa-update-banner />
    }
  `,
  styles: [
    `
      /* This shell's only non-utility CSS is the inset engine — it authors
         two CSS custom properties (--shell-inset-top / --shell-inset-bottom)
         that 6 other files consume via var(...): room-page.scss, room-header.scss,
         comment-input.ts, comments-panel.ts, comment-list.ts. Tailwind utility
         classes cannot author a CSS variable, so this stays. Structural layout
         (grid, sizing, overflow, the desktop sidebar margin) now lives in the
         template's Tailwind classes above. */

      :host {
        display: block;
        --shell-inset-top: var(--app-header-height);
        --shell-inset-bottom: calc(var(--bottom-nav-height) + env(safe-area-inset-bottom, 0px));
      }
      /* .mobile-nav (which --bottom-nav-height reserves space for) is
         display:none above 1024px — the sidenav takes over and consumes no
         vertical space, so nothing needs bottom clearance on desktop. */
      @media (min-width: 1024px) {
        :host {
          --shell-inset-bottom: env(safe-area-inset-bottom, 0px);
        }
      }

      /* Fullscreen routes (login/signup — chromeless auth pages) drop every
         piece of shell chrome on every viewport, and collapse the insets to
         zero so the page itself owns the full 100svh/100dvh and is responsible
         for its own safe-area padding. */
      .fullscreen {
        --shell-inset-top: 0px;
        --shell-inset-bottom: 0px;
      }

      /* .main-wrapper — structural sizing/positioning now lives in the
         template's Tailwind classes (relative block min-h-0 overflow-hidden).
         This rule keeps only the desktop sidebar offset, including the RTL
         flip (the only way to express an RTL-aware margin on a single axis,
         since Tailwind's ms-* utility family isn't generated by content
         detection for this project). */
      @media (min-width: 1024px) {
        .main-wrapper {
          margin-left: var(--sidebar-width);
        }
        :host-context([dir='rtl']) .main-wrapper {
          margin-left: 0;
          margin-right: var(--sidebar-width);
        }
      }

      /* The ONLY scroll container. Fills the slot — header floats above.
         Inset padding comes from --shell-inset-top / --shell-inset-bottom. */
      .app-main-shell {
        padding-top: var(--shell-inset-top);
        padding-bottom: var(--shell-inset-bottom);
        scrollbar-width: thin;
        scrollbar-gutter: stable;
        scrollbar-color: var(--color-neutral-300) transparent;
        -webkit-overflow-scrolling: touch;
      }
      .app-main-shell::-webkit-scrollbar { width: 6px; }
      .app-main-shell::-webkit-scrollbar-thumb {
        background-color: var(--color-neutral-300);
        border-radius: 3px;
      }

      /* Immersive routes (mobile room pages) hide the global header and bottom
         nav. The insets collapse to just the safe-area (mobile) or just the
         still-visible desktop app-header (desktop — sidenav replaces the
         bottom-nav on desktop, so the only chrome that disappears is the
         bottom-nav). */
      .immersive {
        --shell-inset-top: max(env(safe-area-inset-top), var(--space-3));
        --shell-inset-bottom: env(safe-area-inset-bottom);
      }
      @media (min-width: 1024px) {
        .immersive {
          --shell-inset-top: var(--app-header-height);
        }
      }
    `,
  ],
})
export class App {
  private readonly imBootstrap = inject(ImBootstrapService);
  private readonly router = inject(Router);
  readonly pwaUpdate = inject(PwaUpdateService);
  protected readonly activeCallStore = inject(ActiveCallStore);

  private readonly routeFlags = toSignal(
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      map(() => {
        const root = this.router.routerState.snapshot.root;
        return {
          immersive: isRouteFlagSet(root, 'immersive'),
          fullscreen: isRouteFlagSet(root, 'fullscreen'),
        };
      }),
    ),
    { initialValue: { immersive: false, fullscreen: false } },
  );

  readonly immersive = computed(() => this.routeFlags().immersive);
  readonly fullscreen = computed(() => this.routeFlags().fullscreen);

  /**
   * CSS alone can hide the sidenav's content on mobile, but not remove
   * <app-sidenav> from the DOM (a @media query can't drive a template @if).
   * Immersive routes want it not rendered at all on mobile, so this tracks
   * viewport width directly — the one case in this shell where a
   * structural decision (mount or not) requires knowing the viewport, not
   * just the route.
   */
  private readonly isMobileViewport = injectIsMobileViewport();

  readonly hideSidenav = computed(() => this.immersive() && this.isMobileViewport());
}
